[package]
name = "Parallelized_Homomorphic_Operations_in_Rust_for_Enhanced_Performance_in_TFHE_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "x86_64"] }
rayon = "1.5"
num = "0.4"